name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests=false

      - name: Run tests
        run: mvn test

      # - name: Build Docker image
      #   run: docker build -t yourname/electronics-app .

      # - name: Push Docker image
      #   run: |
      #     echo "${{ secrets.docker_pass }}" | docker login -u ${{ secrets.docker }} --password-stdin
      #     docker push yourname/electronics-app
